#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DemoWeather.Droid.Resource", IsApplication=true)]

namespace DemoWeather.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::DemoWeather.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::DemoWeather.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::DemoWeather.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::DemoWeather.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::DemoWeather.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::DemoWeather.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::DemoWeather.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::DemoWeather.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::DemoWeather.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::DemoWeather.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::DemoWeather.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::DemoWeather.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::DemoWeather.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::DemoWeather.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::DemoWeather.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::DemoWeather.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::DemoWeather.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::DemoWeather.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::DemoWeather.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::DemoWeather.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::DemoWeather.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::DemoWeather.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::DemoWeather.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::DemoWeather.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::DemoWeather.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::DemoWeather.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::DemoWeather.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::DemoWeather.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::DemoWeather.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::DemoWeather.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::DemoWeather.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::DemoWeather.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::DemoWeather.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::DemoWeather.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::DemoWeather.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::DemoWeather.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::DemoWeather.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::DemoWeather.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::DemoWeather.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_errorstatus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_successstatus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int paper = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int roundedbg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int roundedbgdark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int splash = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int timg2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int weather_baoxueb = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int weather_baoyub = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int weather_dabaoyub = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int weather_daxueb = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int weather_dayub = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int weather_dongyub = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int weather_duoyunb = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int weather_fuchenb = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int weather_leizhenyub = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int weather_leizhenyubanyoubingbaob = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int weather_maib = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int weather_qing = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int weather_qingb = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int weather_shachenbaob = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int weather_tedabaoyub = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int weather_wub = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int weather_xiaoxueb = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int weather_xiaoyub = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int weather_yangshab = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int weather_yinb = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int weather_yujiaxueb = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int weather_zhenxueb = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int weather_zhenyub = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int weather_zhongxueb = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int weather_zhongyub = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int WeatherIcon = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int zhongdaodayu = 2130837538;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int loadingImage = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int loadingProgressBar = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int loadingProgressWheel = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int textViewStatus = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int loading = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int loadingimage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loadingprogress = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
